CREATE TABLE `bms_1_ro` (
	`w_dt` DATETIME NOT NULL COMMENT '데이터 수집 시간',
	`BMS_STATUS` INT(11) NULL DEFAULT NULL COMMENT '상태',
	`BMS_CHARGE_STATUS` INT(11) NULL DEFAULT NULL COMMENT '충방전 상태',
	`BMS_SOC` INT(11) NULL DEFAULT NULL COMMENT 'SOC',
	`BMS_SOH` INT(11) NULL DEFAULT NULL COMMENT 'SOH',
	`BMS_DC_PWR` INT(11) NULL DEFAULT NULL COMMENT 'DC 전력',
	`BMS_DC_VOLT` INT(11) NULL DEFAULT NULL COMMENT 'DC 전압',
	`BMS_DC_CRNT` INT(11) NULL DEFAULT NULL COMMENT 'DC 전류',
	`BMS_MOD_TEMP_HI` INT(11) NULL DEFAULT NULL COMMENT '모듈 온도 LO',
	`BMS_MOD_TEMP_LO` INT(11) NULL DEFAULT NULL COMMENT '모듈 온도 HI',
	`BMS_MOD_VOLT_HI` INT(11) NULL DEFAULT NULL COMMENT '모듈 전압 LO',
	`BMS_MOD_VOLT_LO` INT(11) NULL DEFAULT NULL COMMENT '모듈 전압 HI',
	`BMS_MAX_SOC` INT(11) NULL DEFAULT NULL COMMENT 'MAX SOC',
	`BMS_MAX_SOH` INT(11) NULL DEFAULT NULL COMMENT 'MAX SOH',
	PRIMARY KEY (`w_dt`),
	INDEX `dt_ky` (`w_dt`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
