CREATE TABLE `ess_4_ro` (
	`w_dt` DATETIME NOT NULL COMMENT '데이터 수집 시간',
	`ACT_PWR` INT(11) NULL DEFAULT NULL COMMENT '유효 전력',
	`REACT_PWR` INT(11) NULL DEFAULT NULL COMMENT '무효 전력',
	`PHASE_RS_VOLT` INT(11) NULL DEFAULT NULL COMMENT 'RS 전압',
	`PHASE_ST_VOLT` INT(11) NULL DEFAULT NULL COMMENT 'ST 전압',
	`PHASE_TR_VOLT` INT(11) NULL DEFAULT NULL COMMENT 'TR 전압',
	`PHASE_R_CRNT` INT(11) NULL DEFAULT NULL COMMENT 'R 전류',
	`PHASE_S_CRNT` INT(11) NULL DEFAULT NULL COMMENT 'S 전류',
	`PHASE_T_CRNT` INT(11) NULL DEFAULT NULL COMMENT 'T 전류',
	`FQ` INT(11) NULL DEFAULT NULL COMMENT '주파수',
	`PF` INT(11) NULL DEFAULT NULL COMMENT '역률',
	`TOTAL_CHARGE_AMT` DOUBLE NULL DEFAULT NULL COMMENT '누적 충전량',
	`TOTAL_DISCHARGE_AMT` DOUBLE NULL DEFAULT NULL COMMENT '누적 방전량',
	INDEX `dt_ky` (`w_dt`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
