CREATE TABLE `pcs_3_ro` (
	`w_dt` DATETIME NOT NULL COMMENT '데이터 수집시간',
	`STATUS` INT(11) NULL DEFAULT NULL COMMENT '상태',
	`CHARGE_STATUS` INT(11) NULL DEFAULT NULL COMMENT '충방전 상태',
	`FAULT` INT(11) NULL DEFAULT NULL COMMENT 'FAULT',
	`DC_PWR` INT(11) NULL DEFAULT NULL COMMENT 'DC 전력',
	`DC_VOLT` INT(11) NULL DEFAULT NULL COMMENT 'DC 전압',
	`DC_CRNT` INT(11) NULL DEFAULT NULL COMMENT 'DC 전류',
	`AC_PWR` INT(11) NULL DEFAULT NULL COMMENT 'AC 전력',
	`PHASE_RS_VOLT` INT(11) NULL DEFAULT NULL COMMENT 'RS 전압',
	`PHASE_ST_VOLT` INT(11) NULL DEFAULT NULL COMMENT 'ST 전압',
	`PHASE_TR_VOLT` INT(11) NULL DEFAULT NULL COMMENT 'TR 전압',
	`PHASE_R_CRNT` INT(11) NULL DEFAULT NULL COMMENT 'R 전류',
	`PHASE_S_CRNT` INT(11) NULL DEFAULT NULL COMMENT 'S 전류',
	`PHASE_T_CRNT` INT(11) NULL DEFAULT NULL COMMENT 'T 전류',
	`FQ` INT(11) NULL DEFAULT NULL COMMENT '주파수',
	`TEMP_IN_PANEL` INT(11) NULL DEFAULT NULL COMMENT 'Temp. In Panel',
	`TARGET_PWR` INT(11) NULL DEFAULT NULL COMMENT 'TARGET 전력',
	INDEX `dt_ky` (`w_dt`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
